<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Rent/sale contracts generated by an office. Each can render to a PDF and
     * carries a due_date used by the maturity-alert system.
     */
    public function up(): void
    {
        Schema::create('contracts', function (Blueprint $table) {
            $table->id();
            $table->foreignId('office_id')->constrained('offices')->onDelete('cascade');
            $table->foreignId('house_id')->constrained('houses')->onDelete('cascade');
            $table->enum('type', ['rent', 'sale']);
            $table->string('party_name');                 // tenant or buyer
            $table->string('party_phone')->nullable();
            $table->string('party_national_id')->nullable();
            $table->decimal('amount', 14, 2);
            $table->enum('payment_cycle', ['once', 'monthly', 'quarterly', 'yearly'])->default('monthly');
            $table->date('start_date');
            $table->date('end_date')->nullable();
            $table->date('due_date')->nullable();         // next payment / maturity date
            $table->enum('status', ['active', 'completed', 'cancelled'])->default('active');
            $table->text('notes')->nullable();
            $table->string('reference')->nullable();       // human-readable contract no.
            $table->string('pdf_path')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('contracts');
    }
};
